### ISSUE TITLE
Resources are not getting destroyed

### ISSUE THREAD

**Issue by hi-artem** [PaloAltoNetworks/terraform-provider-prismacloudcompute#12]
## Describe the bug

After running the code from examples directory, and creating resources everything executes as expected, and results into desired outcome. However, upon destroying newly created resource, the terraform code executes but doesn't delete the resources.

## Expected behavior

run `terraform apply --destroy` leads to destruction of the resources

## Current behavior

resources were never destroyed, but removed from terraform state

## Steps to reproduce

1. terraform apply
2. terraform apply --destroy

**Comment by hi-artem** [comment]
It looks like it is currently the limitation of the API.

**Comment by wfg** [comment]
> It looks like it is currently the limitation of the API.

You're correct. The policy resources are going to have to be built a certain way to compensate.

In Compute, each policy type is made up of rules. Compute stores a _single_ policy for each policy type. Deleting a policy doesn't make sense to Compute. Instead, you update (PUT) the policy to have a new set of rules.

In Terraform, this means that you will only have a single policy resource and edit its content.
```
 prismacloudcompute_policiesvulnerabilityimages
+----------------------------------------------+
| rule 1                                       |
| rule 2                                       |
| rule 3                                       |
| ...                                          |
| rule n                                       |
+----------------------------------------------+
```

**Comment by hi-artem** [comment]
> > It looks like it is currently the limitation of the API.
> 
> You're correct. The policy resources are going to have to be built a certain way to compensate.
> 
> In Compute, each policy type is made up of rules. Compute stores a _single_ policy for each policy type. Deleting a policy doesn't make sense to Compute. Instead, you update (PUT) the policy to have a new set of rules.
> 
> In Terraform, this means that you will only have a single policy resource and edit its content.
> 
> ```
>  prismacloudcompute_policiesvulnerabilityimages
> +----------------------------------------------+
> | rule 1                                       |
> | rule 2                                       |
> | rule 3                                       |
> | ...                                          |
> | rule n                                       |
> +----------------------------------------------+
> ```

Gotcha! That makes perfect sense. 

Another question then, how would I add multiple rules to the policy then?

Would it look something like that:

```hcl
resource "prismacloudcompute_policiesruntimecontainer" "example2" {
  learningdisabled = false
  rules {
    name = "example container runtime rule 1"
    collections {
      name = "All"
    }
    wildfireanalysis = "alert"
    processes = {
      "effect" : "alert"
    }
    network = {
      "effect" : "alert"
    }
    dns = {
      "effect" : "disable"
    }
    filesystem = {
      effect = "alert"
    }
  }

  rules {
    name = "example container runtime rule 2"
    collections {
      name = "All"
    }
    wildfireanalysis = "alert"
    processes = {
      "effect" : "alert"
    }
    network = {
      "effect" : "alert"
    }
    dns = {
      "effect" : "disable"
    }
    filesystem = {
      effect = "alert"
    }
  }
}

**Comment by wfg** [comment]
@hi-artem That's the plan :). Although the logic for multiple rules hasn't been built yet.

**Comment by hi-artem** [comment]
@wfg Copy that! I am closing the issue since it is not relevant to the policy workflow (as shown above).
