### ISSUE TITLE
Step 2 - Cloning the Repository

### ISSUE THREAD

**Issue by afdsioh234** [PaloAltoNetworks/terraform-provider-prismacloudcompute#20]
When I try to clone the repository, I always get the error below about the pubkey permission denied, not sure if I am doing something wrong - 

[ec2-user@ip-172-24-50-236 ~]$ git clone git@github.com:PaloAltoNetworks/terraform-provider-prismacloudcompute.git $GOPATH/src/github.com/terraform-providers/terraform-provider-prismacloudcompute && cd $_
Cloning into '/home/ec2-user/go/src/github.com/terraform-providers/terraform-provider-prismacloudcompute'...
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by wfg** [comment]
That step assumes you have your SSH keys set up. Use the HTTPS URL if not:
```bash
git clone https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute.git $GOPATH/src/github.com/terraform-providers/terraform-provider-prismacloudcompute && cd $_
```

**Comment by afdsioh234** [comment]
Thanks!! I used https and I was able to get the repository (I'll fix the ssh thing on the backend), when I try to run the make command, I get the below errors - (I am running an amazon ec2 instance, not sure if I need to change the OS command or something along those lines)

[ec2-user@ip-172-24-50-236 terraform-provider-prismacloudcompute]$ make install                                                                                                              OS_ARCH=darwin_amd64 VERSION=0.0.2-test1
go build -o terraform-provider-prismacloudcompute
prismacloudcompute/data_source_policies_compliance_host.go:7:2: no required modu                                                                                                             le provides package github.com/paloaltonetworks/prisma-cloud-compute-go/policy/p                                                                                                             olicyComplianceHost; to add it:
        go get github.com/paloaltonetworks/prisma-cloud-compute-go/policy/policy                                                                                                             ComplianceHost
prismacloudcompute/data_source_policies_runtime_host.go:7:2: no required module                                                                                                              provides package github.com/paloaltonetworks/prisma-cloud-compute-go/policy/poli                                                                                                             cyRuntimeHost; to add it:
        go get github.com/paloaltonetworks/prisma-cloud-compute-go/policy/policy                                                                                                             RuntimeHost
prismacloudcompute/data_source_policies_vulnerability_host.go:7:2: no required m                                                                                                             odule provides package github.com/paloaltonetworks/prisma-cloud-compute-go/polic                                                                                                             y/policyVulnerabilityHost; to add it:
        go get github.com/paloaltonetworks/prisma-cloud-compute-go/policy/policy                                                                                                             VulnerabilityHost
make: *** [build] Error 1
