### ISSUE TITLE
Configure Provider Using Variable Rather Than Config File

### ISSUE THREAD

**Issue by hi-artem** [PaloAltoNetworks/terraform-provider-prismacloudcompute#30]
### Is your feature request related to a problem?

We have a use case where using config file presents an issue: 
Running Terraform in automation where we are using Vault as a secret storage. We want to use Vault data source to pull secrets and configure provider. It is problematic with config file.

### Describe the solution you'd like

Allow to configure provider the following way: 

```hcl
provider "prismacloudcompute" {
  username = "admin"
  password = "secret"
  console_url = "https://exmaple.com/"
}
```

**Comment by hi-artem** [comment]
There is actually a bug preventing this from functioning properly. I opened pr to fix it - https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/pull/31

**Comment by wfg** [comment]
Awesome! Closing.

**Comment by hi-artem** [comment]
@wfg

**Comment by wfg** [comment]
> I'm still broken, looks like there's not a new release cut with the fix, can you update?

Sure can. We'll push an update Monday that'll include this fix.
