### ISSUE TITLE
Add admission policies resource

### ISSUE THREAD

**Issue by hi-artem** [PaloAltoNetworks/terraform-provider-prismacloudcompute#32]
### Is your feature request related to a problem?

We want to be able to manage our Admission policies using Terraform

### Describe the solution you'd like

Add Terraform resource allowing to manage Admission policies

### Additional Context

It looks like this would require additions to https://github.com/PaloAltoNetworks/prisma-cloud-compute-go

**Comment by hi-artem** [comment]
I will start working on this issue myself, but just want to open PR to track it.

**Comment by wfg** [comment]
Can you pull main branch and test using the SDK's main branch as well? If all works as expected, I'll close this issue and tag for release.

**Comment by hi-artem** [comment]
```sh
❯ make
go build -o terraform-provider-prismacloudcompute
# github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/prismacloudcompute/convert
prismacloudcompute/convert/admission.go:8:56: undefined: policy.AdmissionRule
prismacloudcompute/convert/admission.go:9:24: undefined: policy.AdmissionRule
prismacloudcompute/convert/admission.go:14:18: undefined: policy.AdmissionRule
prismacloudcompute/convert/admission.go:28:34: undefined: policy.AdmissionRule
make: *** [build] Error 2
```

I think [prisma-cloud-compute-go](https://github.com/PaloAltoNetworks/prisma-cloud-compute-go) needs to be tagged, and [go.mod](https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/blob/bbe49715820821b9f3f8a88796e1c9e13b722219/go.mod#L7) needs to be updated.

**Comment by wfg** [comment]
@hi-artem did you do a
```bash
go get github.com/paloaltonetworks/prisma-cloud-compute-go@main
```
beforehand? That should update go.mod without having to tag the SDK. I use that method during my testing.

**Comment by hi-artem** [comment]
@wfg ahh... i haven't! works now. I tested the main branch of the provider, and everything looks go.

**Comment by hi-artem** [comment]
I will close it, since it is in [v0.2.0](https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/releases/tag/v0.2.0)
