### ISSUE TITLE
Support for Managing Tenant Consoles using prismacloudcompute provider

### ISSUE THREAD

**Issue by jhabikal21** [PaloAltoNetworks/terraform-provider-prismacloudcompute#34]
### Is your feature request related to a problem?

It is difficult to manage individual Tenant consoles (projects) in a single terraform project as we use self-hosted consoles on Kubernetes and not each TL Project has its URL instead uses internal k8 URLs.

### Describe the solution you'd like

We would like to manage individual Tenant consoles (projects) in a single terraform project by using an alias in provider.

### Describe alternatives you've considered

For now, the alternative would be to use the URL of each TL Tenant project and create a provider however this doesn't work for our requirement as we use an internal k8 URL instead of a public domain.

**Comment by jhabikal21** [comment]
If you see, you mentioned 2 providers however I can't add my project name in `creds_0.json`.
```
{
  "console_url": "https://foo.bar.com",
  **"tenant_project": "ABC",**
  "username": "myUsername",
  "password": "myPassword"
}
```

![image](https://user-images.githubusercontent.com/35531767/145521621-4254624e-1c5b-4877-a1b8-85404fc81baf.png)
We would like to manage these all projects from our single terraform projects using multiple aliases.

Please let me know if the above information is still not clear. Thanks

**Comment by wfg** [comment]
Thanks for the feedback @jhabikal21. I'm working on this one now. Hope to have something by the end of the week.

**Comment by wfg** [comment]
Added in v0.4.0. Please open a new issue if you have any problems with it @jhabikal21
