### ISSUE TITLE
Data Resource to Manage Custom Rules

### ISSUE THREAD

**Issue by hi-artem** [PaloAltoNetworks/terraform-provider-prismacloudcompute#37]
### Is your feature request related to a problem?

We should have a way to get ID for Custom Rules. It will be particularly useful for the Rules that pre-exist in Prisma Cloud Compute. 

### Describe the solution you'd like

```hcl
data "prismacloudcompute_custom_rule" "rule" {
  name = "Block log4j"
}

resource "prismacloudcompute_container_runtime_policy" "ruleset" {
    custom_rule {
      action = "incident"
      effect = "block"
      id     = data.prismacloudcompute_custom_rule.rule
    }
}
```

**Comment by wfg** [comment]
In v0.3.0. Thanks for the contributions @hi-artem!
