### ISSUE TITLE
Add graceDaysPolicy for Vulnerability Policies

### ISSUE THREAD

**Issue by hi-artem** [PaloAltoNetworks/terraform-provider-prismacloudcompute#41]
## Describe the problem

It is currently a limitation of the provider. The `prismacloudcompute_host_vulnerability_policy` and `prismacloudcompute_ci_image_vulnerability_policy` resources only support `graceDays` directive, but not `graceDaysPolicy`.

One common issue here is for users implementing FedRAMP, there is no way to define the recommended policy using just `graceDays`. Since the period for various severity should be different.

## Suggested fix

Add `graceDaysPolicy` directive to the affected resources.

**Comment by hi-artem** [comment]
I mislabeled this one - it should be `enhancement`

**Comment by hi-artem** [comment]
i will work on this issue since it is currently a blocker for us

**Comment by wfg** [comment]
Added with #42
