### ISSUE TITLE
Support authenticating without config

### ISSUE THREAD

**Issue by jasonckeating** [PaloAltoNetworks/terraform-provider-prismacloudcompute#43]
## Describe the bug

Authentication with username/password still does not work.

## Expected behavior

Configuring authentication with usernames and passwords should work without errors.

## Current behavior

When configuring compute with the following:
```
provider "prismacloudcompute" {
  # Configuration options  
  username    = var.PRISMACLOUD_USERNAME
  password    = var.PRISMACLOUD_PASSWORD
  console_url = "us-west1.cloud.twistlock.com/us-12345678"
}
```

The following error is experienced.
```
╷
│ Error: error creating API client: Post "/api/v1/authenticate": unsupported protocol scheme ""
│ 
│   with provider["registry.terraform.io/paloaltonetworks/prismacloudcompute"],
│   on main.tf line 15, in provider "prismacloudcompute":
│   15: provider "prismacloudcompute" {
│ 
╵
```

## Steps to reproduce

1. Configure Prisma Cloud Compute without a config file.
2. tf init
3. tf plan

## Context

Cannot use the Prisma Cloud Compute provider to manage large number of accounts int he compute section of Prisma.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by jasonckeating** [comment]
Adding another error using v0.3.0 of this provider.
```
│ 
│ Error: error creating API client: error authenticating: error POSTing to authenticate endpoint: Post "/api/v1/authenticate?project=": unsupported protocol scheme ""
│ 
│   with provider["registry.terraform.io/paloaltonetworks/prismacloudcompute"],
│   on main.tf line 15, in provider "prismacloudcompute":
│   15: provider "prismacloudcompute" {
│ 
```

**Comment by wfg** [comment]
@jasonckeating thanks for bringing this to my attention. There was a problem with how I was building the URL that only presented itself when the Console URL had a path other than `/` (so all SaaS Consoles). It's fixed in v0.4.0.

**Comment by jasonckeating** [comment]
Getting a similar error on v0.4.0:
```
╷
│ Error: error creating API client: error authenticating: error POSTing to authenticate endpoint: Post "us-west1.cloud.twistlock.com/us-12345678/api/v1/authenticate": unsupported protocol scheme ""
│ 
│   with provider["registry.terraform.io/paloaltonetworks/prismacloudcompute"],
│   on main.tf line 15, in provider "prismacloudcompute":
│   15: provider "prismacloudcompute" {
│ 
```

**Comment by wfg** [comment]
Ahh.. The `https://` prefix is required. In a future version, I'll have it default to HTTPS if not supplied.

**Comment by jasonckeating** [comment]
ah, thanks, updated and got the plan
