### ISSUE TITLE
Collections throws 429 when adding > 1 collection

### ISSUE THREAD

**Issue by jasonckeating** [PaloAltoNetworks/terraform-provider-prismacloudcompute#58]
## Describe the bug

Programmatically adding all accounts as a collection to Prisma.

## Expected behavior

Each collection defined in code is created in Prisma Cloud

## Current behavior

Every collection creation fails with a 429 error code.

## Steps to reproduce

1. Create a for loop collection that creates more than one.
```
resource "prismacloudcompute_collection" "this" {
  for_each          = tomap(local.all_accounts)
  name              = "${each.value.name} - ${each.value.id}"
  description       = "All resources from the ${each.value.name} account."
  account_ids       = [each.value.id]
  application_ids   = ["*"]
  clusters          = ["*"]
  code_repositories = ["*"]
  containers        = ["*"]
  functions         = ["*"]
  images            = ["*"]
  labels            = ["*"]
  namespaces        = ["*"]
}
```
2. terraform apply
3. observe the error
```
 Error: error creating collection '{AccountIds:[12345] AppIds:[*] Clusters:[*] CodeRepos:[*] Color:#A020F0 Containers:[*] Description:All resources from the sample-dev account. Functions:[*] Hosts:[*] Images:[*] Labels:[*] Name:sample-dev - 12345 Namespaces:[*]}': Non-OK status: 429
│ 
│   with prismacloudcompute_collection.this["sample-dev"],
│   on collections.tf line 28, in resource "prismacloudcompute_collection" "this":
│   28: resource "prismacloudcompute_collection" "this" {
│ 
```
4.

## Context

We are wanting to provide collections for each account so Devleopment teams can see their vulnerabilities for only their accounts.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by hi-artem** [comment]
@jasonckeating this was solved, but never released https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/pull/55

**Comment by hi-artem** [comment]
@wfg can the latest main be released and published to tf registry?

**Comment by wfg** [comment]
@jasonckeating @hi-artem Sure, I'll push a new tag tomorrow morning.

**Comment by hi-artem** [comment]
Awesome! Thank you

**Comment by wfg** [comment]
v0.7.0 released

**Comment by hi-artem** [comment]
@jasonckeating can you check this again with 0.7.0 release?

**Comment by jasonckeating** [comment]
@hi-artem tried again on 0.7.0.

terraform apply took 1 hour on an attempt to add new 100 collections,
then failed at the end of an hour with this error

```Non-OK status: 409```
