### ISSUE TITLE
Cannot Disable Learning for Image Runtime Policy

### ISSUE THREAD

**Issue by hi-artem** [PaloAltoNetworks/terraform-provider-prismacloudcompute#59]
## Describe the bug

The `learning_disabled` directive of `prismacloudcompute_container_runtime_policy` is not behaving as expected.

## Expected behavior

Assuming the TF is the following:

```hcl
resource "prismacloudcompute_container_runtime_policy" "ruleset" {
  learning_disabled = true
}
```

The `terraform apply` should disable the learning.

## Current behavior

It doesn't disable the learning.

## Possible solution

Review `prismacloudcompute_container_runtime_policy` resource source code to find a bug

## Steps to reproduce

1. Use template from above
2. Run terraform apply
3. Run it again; plan is the same
4. Repeat to confirm the changes weren't applied

## Your Environment

0.7.0 and 22.06.197 self-hosted

**Comment by maxboynton** [comment]
Issue has been addressed in the v0.8.0 release (https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/pull/71).
