### ISSUE TITLE
Only 1 custom compliance is created in Prisma even if multiple prismacloudcompute_custom_compliance resources are set

### ISSUE THREAD

**Issue by aymericpineau** [PaloAltoNetworks/terraform-provider-prismacloudcompute#63]
PrismaCloudCompute 0.7.0

## Describe the bug

Using multiple "**prismacloudcompute_custom_compliance**" resource blocks causes only 1 compliance rule to be created in PrismaCloud Console.

Note: Once "terraform apply" is done, all "**prismacloudcompute_custom_compliance**" resources are in the terraform state but only one compliance rule is created in the Prisma Cloud Console.

## Expected behavior

All "**prismacloudcompute_custom_compliance**" should be created and visible in the PrismaCloud Console

**Comment by nk-rao** [comment]
Same issue we are also facing

**Comment by maxboynton** [comment]
Issue has been addressed in the v0.8.0 release (https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/pull/71).
