### ISSUE TITLE
prismacloudcompute_alertprofile is missing parameters

### ISSUE THREAD

**Issue by aymericpineau** [PaloAltoNetworks/terraform-provider-prismacloudcompute#64]
## Describe the bug

The "**prismacloudcompute_alertprofile**" Terraform resource is missing some parameters in the "**alert_triggers**" block.

## Expected behavior

The PrismaCloudCompute Terraform Provider should be able to setup everything that is available in the GUI.

## Current behavior

In the GUI (**Compute > Manage/Alerts > Manage > "My alert Provider" > Triggers**) the following parameters cannot be configured using "**prismacloudcompute_alertprofile**" Terraform resource:
- Vulnerabilities > VM images vulnerabilities
- Vulnerabilities > Immediately alert for deployed resources
- Compliance > VM images compliance

**Comment by maxboynton** [comment]
Issue has been addressed in the v0.8.0 release (https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/pull/71).
