### ISSUE TITLE
prismacloudcompute_alertprofile always shows changes on the "alert_triggers" block

### ISSUE THREAD

**Issue by aymericpineau** [PaloAltoNetworks/terraform-provider-prismacloudcompute#65]
prismacloudcompute 0.7.0

## Describe the bug

Doing "terraform plan/apply" over and over again **wihout any change in the Terraform code** shows the "**prismacloudcompute_alertprofile > alert_triggers**" block to always create every single item

## Expected behavior

Once created and no updates are made, the "**prismacloudcompute_alertprofile > alert_triggers**" block should not show any update in the **terraform plan/apply**.

## Current behavior

Every single time terraform plan/apply is run, Terraform shows the "**prismacloudcompute_alertprofile > alert_triggers**" block to create every single item.
![image](https://user-images.githubusercontent.com/41776378/193546803-a2a865ba-5a94-48ba-892a-d59d58c408d7.png)

**Comment by maxboynton** [comment]
As of the latest release, this issue will only occur if there are triggers (the configuration block for which has now been renamed to `policy`) specified that aren't relevant to webhook alerts, which are the only alert profile types supported presently. Below is a list of all the policies that apply to webhook alerts:

- admission
- app_embedded_app_firewall
- app_embedded_runtime
- container_app_firewall
- container_compliance_scan
- container_vulnerability
- dokcer
- host_app_firewall
- host_compliance_scan
- host_runtime
- host_vulnerability
- kubernetes_audit
- network_firewall
- registry_vulnerability
- serverless_app_firewall
- serverless_runtime
- vm_compliance
- waas_health

If any of the policies that are supported by the provider but are NOT in the above list are specified in the template, this issue will occure.
