### ISSUE TITLE
Terraform resource for "Compute > Manage/Cloud Accounts > Add Account" is missing

### ISSUE THREAD

**Issue by aymericpineau** [PaloAltoNetworks/terraform-provider-prismacloudcompute#66]
PrismaCloudCompute 0.7.0

## Describe the bug

Terraform resource for "**Compute > Manage/Cloud Accounts > Add Account**" is missing.

The problem is that it is required to:
- Add registries (Compute > Defend/Vulnerabilities > Images > Registry Settings > Add Registry). See the "Credential" item.
- Enable Discovery features (Cloud Discovery + VM Tags + Serverless Radar)

## Expected behavior

Terraform resource for "Compute > Manage/Cloud Accounts > Add Account" should exist.
Having this resource available is mandatory for automatic and at scale cloud accounts onboarding

## Current behavior

Terraform resource for "Compute > Manage/Cloud Accounts > Add Account" does not exist.

## Other information
This issue is linked to theses 2 issues:
- https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/issues/61
- https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/issues/62

Dealing with this issue and having the Terraform resource for setting up "**Compute > Manage/Cloud Accounts > Add Account**" would allow to close the 2 issues above (61 + 62).
Indeed, it was before required to create Credentials Store in "Compute > Authentication > Credential Store".

Cheers,
Aymeric PINEAU

**Comment by maxboynton** [comment]
Issue has been addressed in the v0.8.0 release (https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/pull/71).

Please note that the newly created resource for this object is at an early stage. In future updates, the property descriptions, optional/required property designations and tests/examples will be expanded.
